검색어 자동완성시 구, 동 포함한 검색어 인식 구현
CollectingBox/server pull request #98
Opened 2024-05-16 07:11 UTC by Doyeon04

## 💡 작업 내용
- [x] 구, 동 포함한 검색어 인식해 자동완성 목록 조회
- [x] 검색어 인식시 공백 처리
- [x] 기존 코드 리팩토링

## 💡 자세한 설명
검색어에 공백을 포함한 경우의 케이스들을 처리했습니다. 

1. 구와 동 사이 공백 하나일 경우 처리 ex) "강남구 개포1동" 
2. 구와 동 사이 공백 여러개일 경우 처리 ex) "강남구   개포1동" 
3. 맨 앞이나 맨 끝에 공백이 있을 경우 처리 ex) "  강남구 개포1동  " 

## ✅ 셀프 체크리스트
- [x] PR 제목을 형식에 맞게 작성했나요?
- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있나요?
- [x] 이슈는 close 했나요?
- [x] Reviewers, Labels, Projects를 등록했나요?
- [x] 작업 도중 문서 수정이 필요한 경우 잘 수정했나요?
- [x] 테스트는 잘 통과했나요?
- [x] 불필요한 코드는 제거했나요?

closes #97

2024-05-16 15:27 UTC, Hanjaemo requested changes

2024-05-16 15:27 UTC, Hanjaemo commented on src/main/java/contest/collectingbox/module/autocomplete/domain/AutoCompleteRepositoryImpl.java
> +                .and(dongInfo.dongNm.contains(split[split.length-1]));
" 강남구 청담동 "처럼 앞뒤에 공백이 오게 되면 split의 0번째 요소는 ""이라는 빈 문자열이 됩니다.
이를 해결하기 위해 trim 메서드를 사용해서 앞뒤 공백을 제거해줘야 할 것 같아요.

2024-05-16 22:54 UTC, Doyeon04 commented on src/main/java/contest/collectingbox/module/autocomplete/domain/AutoCompleteRepositoryImpl.java
> +                .and(dongInfo.dongNm.contains(split[split.length-1]));
컨트롤러에서 query 넘길 때 trim()해 앞뒤 공백 제거됩니다!

2024-05-17 05:14 UTC, Hanjaemo approved these changes

2024-05-17 06:14 UTC, merged